require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
    NewCops: enable

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Max: 40

RSpec/MultipleExpectations:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/TrailingCommaInArguments:
  Exclude:
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false
